---
title: "rahil_things"
output: html_document
date: "2023-05-27"
---

```{r}
library(data.table)
library(rstan)
library(rstanarm)
library(forcats)
library(dplyr)
library(bayesplot)

#Formatting Data to Make easier to Cluster
traindf <- t(Irish_adj_train$indCons)
traindf <- data.frame(ID = rownames(traindf), traindf, row.names = NULL)

testdf <- t(Irish_adj_test$indCons)
testdf <- data.frame(ID = rownames(testdf), testdf, row.names = NULL)

extratrain <- Irish_adj_train$extra
extratest <- Irish_adj_test$extra

# Merge training and testing data frames with the cluster data frame
merged_train <- merge(traindf, hc4, by = "ID")[,-1]
merged_test <- merge(testdf, hc4, by = "ID")[,-1]

# Data Frame with each cluster with summed electricity demand
traindt <- data.table(merged_train)
sumtrain_dt <- traindt[, lapply(.SD, sum), by = cluster]

testdt <- data.table(merged_test)
sumtest_dt <- testdt[, lapply(.SD, sum), by = cluster]
```


```{r}
extratest$dow <- fct_collapse(extratest$dow,
                              Weekend = c('Sun', 'Sat'),
                              Weekday = c('Mon', 'Tue', 'Wed', 'Thu', 'Fri'))

extratrain$dow <- fct_collapse(extratrain$dow,
                              Weekend = c('Sun', 'Sat'),
                              Weekday = c('Mon', 'Tue', 'Wed', 'Thu', 'Fri'))
```


```{r}
# Extract First Time Series
one <- data.table(cbind(t(sumtrain_dt[1,-1]), extratrain$tod))

one <- split(one$V1, as.factor(one$V2))

one <- as.data.table(one)[-326,]

#get extra data for TOD == 0
ex <- extratrain[extratrain$tod == 0,]

dum <- model.matrix(~ ex$dow - 1)
```


```{r}
# Combine t
tY <- c(unlist(as.vector(one[,1])), 0)

tX <- rbind(matrix(rep(0, ncol(one)), nrow = 1), as.matrix(one))

X <- cbind(tY, tX)[c(-1, -nrow(tX)),]

X <- cbind(X, ex$toy[-1], ex$temp[-1])

X <- scale(X, center = FALSE, scale = FALSE)

X <- cbind(X, dum[-1,])

Y <- X[,1]

X <- X[,-1]
```


```{r}
dataprocess <- function(cluster, time, sumdata, extra){
  
  t <- data.table(cbind(t(sumdata[cluster,-1]), extra$tod))
  
  t <- split(t$V1, as.factor(t$V2))
  
  t <- as.data.table(t)[-326,]
  
  ex <- extra[extra$tod == time,]
  
  dum <- model.matrix(~ ex$dow - 1)
  
  tY <- c(unlist(as.vector(t[,1])), 0)

  tX <- rbind(matrix(rep(0, ncol(t)), nrow = 1), as.matrix(t))
  
  X <- cbind(tY, tX)[c(-1, -nrow(tX)),]

  X <- cbind(X, ex$toy[-1], ex$temp[-1])
  
  means <- colMeans(X)

  X <- scale(X, center = TRUE, scale = FALSE)
  
  X <- cbind(X, dum[-1,])

  Y <- X[,1]

  X <- X[,-1]
  
  slr <- list(modelM = X, response = Y, colmean = means)
  
  class(slr) <- 'datap'
  return(slr)
}
```


```{r}
stan_code <- "data {
  int<lower=0> N; // number of data items
  int<lower=0> K; // number of predictors
  matrix[N, K] x; // predictor matrix
  vector[N] y; // outcome vector
}
parameters {
  vector[K] beta; // coefficients for predictors
  real<lower=0> tau; // precision parameter
}
transformed parameters {
  real<lower=0> sigma; // standard deviation
  sigma = 1 / sqrt(tau); // Convert precision to standard deviation
}
model {
  tau ~ gamma(2, 0.1); // Gamma prior on the precision
  beta ~ normal(0, 100); // Normal prior on the coefficients
  y ~ normal(x * beta, sigma); // Likelihood
}

generated quantities {
 real y_rep[N];

 for (n in 1:N) {
 y_rep[n] = normal_rng(x[n] * beta, sigma);
 }

}"



# Data for Stan
stan_data <- list(
    N = length(Y),
    K = ncol(X),
    x = X,
    y = Y
  )
  
# Compile and fit the model
fit <- stan(model_code = stan_code, data = stan_data, iter = 2000, chains = 4)
```

```{r}
posterior <- extract(fit)
stan_dens(fit, pars =  (dimnames(fit)[3])$parameters[1:25])
stan_dens(fit, pars =  (dimnames(fit)[3])$parameters[25:51])
plot(posterior$beta[,5], type = 'l')
```


```{r}
plot(Y)
lines(colMeans(posterior$y_rep))
```
```{r}
library(lubridate)
#Test
test1 <- data.table(cbind(t(sumtest_dt[1,-1]), extratest$tod))

test1 <- split(test1$V1, as.factor(test1$V2))

test1 <- as.data.table(test1)

datetest1 <- cbind(test1, yday(extratest$dateTime)[1:length(extratest$dateTime) %% 48 == 1])
```

```{r}
#Train
train1 <- data.table(cbind(t(sumtrain_dt[1,-1]), extratrain$tod))

train1 <- split(train1$V1, as.factor(train1$V2))

train1 <- as.data.table(train1)

datetrain1 <- cbind(train1, yday(extratrain$dateTime)[1:length(extratrain$dateTime) %% 48 == 1])
```

```{r}
modelTest <- matrix(ncol = 49)
for (i in 1:nrow(datetest1)){
  day <- datetest1$V2[i]
  rw <- datetrain1[datetrain1$V2 == (day-1), ]
  if (nrow(rw) == 0){
    rw <- datetest1[datetest1$V2 == (day-1), ]
  }
  modelTest <- rbind(modelTest, rw, use.names = FALSE)
}


modelTest <- modelTest[-1, -49]

exTest <-extratest[extratest$tod == 0,]

dumTest <- model.matrix(~ exTest$dow - 1)

modelTest <- cbind(modelTest, exTest$toy, exTest$temp, dumTest)
```

```{r}
library(ggplot2)

plotdf <- as.data.frame(cbind(1:nrow(test1), test1[,1]))

ggplot(plotdf) + geom_point(aes(x = plotdf$V1, y = plotdf[,2]))

meanbeta <- as.matrix(colMeans(posterior$beta), ncol = 1)

modelTest0 <- as.matrix(modelTest)

estimate0 <-   modelTest0 %*% meanbeta

ggplot(plotdf) + geom_point(aes(x = V1, y = plotdf[,2])) + geom_line(aes(x = V1, y = estimate0, colour = 'Mean Posterior'))
```

